// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8PbTkGjVutd_J4-Y_SfME9EqnzPAp9uI',
    appId: '1:924966695400:web:e4e3328bf2181d3579745d',
    messagingSenderId: '924966695400',
    projectId: 'ecommerce-15fa4',
    authDomain: 'ecommerce-15fa4.firebaseapp.com',
    storageBucket: 'ecommerce-15fa4.firebasestorage.app',
    measurementId: 'G-RQW4LDECSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxPpUL02pz3uQMq_1SkbjUiFbfSigchRQ',
    appId: '1:924966695400:android:e1368e98115d49dc79745d',
    messagingSenderId: '924966695400',
    projectId: 'ecommerce-15fa4',
    storageBucket: 'ecommerce-15fa4.firebasestorage.app',
  );
}
